Updated Ubuntu version from 14.04 to 16.04 to avoid a docker-build error below.
ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).